<?php

namespace AppBundle\Entity;

/**
 * PlankRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlankRepository extends \Doctrine\ORM\EntityRepository
{
}
